#!/usr/bin/env python

default = { "color": "white", "ecolor": "black", "edgecolor": "black", "hatch": " "   }
ame     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "/"   }
ba      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "|"   }
bel     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "-"   }
cas     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "xx"  }
ce      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "O"   }
cjb     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "X"   }
cpv     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "."   }
cxj     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": ".."  }
df      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "x"   }
gyn     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "*"   }
laj     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "**"  }
lda     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "+"   }
mao     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "++"  }
mg      = { "color": "blue",  "ecolor": "blue",  "edgecolor": "blue",  "hatch": "@"   }
mgf     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "oo"  }
nat     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "@@"  }
pe      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "0"   }
pr      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "/"   }
rj      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "///" }
rs      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "o"   }
sca     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "+++" }
sc      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "ooo" }
sjc     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "..." }
sjp     = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": "00"  }
sp      = { "color": "white", "ecolor": "red",   "edgecolor": "red",   "hatch": " "   }
vix     = { "color": "white", "ecolor": "red",   "edgecolor": "blue",  "hatch": "xxx" }